language: node_js
node_js:
  - lts/*

cache:
  directories:
    - "$HOME/.npm"

install:
  - npm ci

script:
  - npm run lint
  - npm test

after_success:
  - npm test -- --coverage

after_script:
  - cat ./coverage/lcov.info | coveralls
